name: untitled7
description: A new Flutter project

environment:
  sdk: '^3.2.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

version: 1.0.0
build_name: 1.0.0
build_number: 1
